"""A readable data catalog: schema + scanner findings + contracts, joined into one view.

The catalog documents; `check` enforces. Output is deterministic (no timestamps), so
regenerating it only changes the file when something real changed.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

from data_warden.check import Violation
from data_warden.contracts import Contract
from data_warden.scan import Finding


@dataclass(frozen=True)
class CatalogColumn:
    name: str
    data_type: str
    pii_type: str | None  # the declared type if there is one (humans are authoritative)
    source: str | None  # "detected + declared", "detected only", "declared only" or None
    confidence: float | None  # scanner confidence, when the scanner found it


@dataclass(frozen=True)
class CatalogTable:
    name: str
    has_contract: bool
    owner: str | None
    retention_days: int | None
    columns: list[CatalogColumn]
    errors: int
    warnings: int

    @property
    def pii_columns(self) -> list[CatalogColumn]:
        return [c for c in self.columns if c.pii_type]


@dataclass(frozen=True)
class Catalog:
    tables: list[CatalogTable]


def _column(
    name: str, data_type: str, finding: Finding | None, declared: str | None
) -> CatalogColumn:
    if finding and declared:
        source = "detected + declared"
    elif finding:
        source = "detected only"
    elif declared:
        source = "declared only"
    else:
        source = None
    pii_type = declared or (finding.pii_type if finding else None)
    return CatalogColumn(name, data_type, pii_type, source, finding.confidence if finding else None)


def build_catalog(
    columns: dict[str, list[tuple[str, str]]],
    findings: list[Finding],
    contracts: dict[str, Contract],
    violations: list[Violation],
) -> Catalog:
    detected = {(f.table, f.column): f for f in findings}
    tables: list[CatalogTable] = []
    for table, table_columns in sorted(columns.items()):
        contract = contracts.get(table)
        declared = contract.pii_columns if contract else {}
        rows = [
            _column(name, data_type, detected.get((table, name)), declared.get(name))
            for name, data_type in table_columns
        ]
        in_database = {name for name, _ in table_columns}
        # A contract may declare a column that is not in the database: show it, do not hide it.
        rows += [
            _column(name, "not found in database", None, declared[name])
            for name in sorted(set(declared) - in_database)
        ]
        issues = [v for v in violations if v.table == table]
        tables.append(
            CatalogTable(
                name=table,
                has_contract=contract is not None,
                owner=contract.owner if contract else None,
                retention_days=contract.retention_days if contract else None,
                columns=rows,
                errors=sum(v.severity == "error" for v in issues),
                warnings=sum(v.severity == "warning" for v in issues),
            )
        )
    return Catalog(tables)


def to_dict(catalog: Catalog) -> dict:
    data = asdict(catalog)
    for table in data["tables"]:
        for column in table["columns"]:
            if column["confidence"] is not None:
                column["confidence"] = round(column["confidence"], 4)
    return data


def _cell(value: object) -> str:
    text = "-" if value in (None, "") else str(value)
    return text.replace("|", "\\|")


def _status(table: CatalogTable) -> str:
    if table.errors:
        return f"{table.errors} error(s), {table.warnings} warning(s)"
    if table.warnings:
        return f"ok, {table.warnings} warning(s)"
    return "ok" if table.pii_columns else "no personal data"


def render_markdown(catalog: Catalog) -> str:
    pii_tables = [t for t in catalog.tables if t.pii_columns]
    pii_columns = sum(len(t.pii_columns) for t in catalog.tables)
    errors = sum(t.errors for t in catalog.tables)
    lines = [
        "# Data catalog",
        "",
        "Generated by data-warden from the database schema, scanner findings and data contracts.",
        "Do not edit by hand: change the contracts and regenerate.",
        "",
        f"{len(catalog.tables)} tables, {len(pii_tables)} with personal data, "
        f"{pii_columns} personal-data columns, {errors} error(s) from `check`.",
        "",
        "## Tables",
        "",
        "| Table | Owner | Retention | Personal-data columns | Status |",
        "| --- | --- | --- | --- | --- |",
    ]
    for t in catalog.tables:
        retention = f"{t.retention_days} days" if t.retention_days else None
        lines.append(
            f"| [{_cell(t.name)}](#{t.name.lower()}) | {_cell(t.owner)} | {_cell(retention)} "
            f"| {len(t.pii_columns)} | {_status(t)} |"
        )
    for t in catalog.tables:
        lines += ["", f"## {t.name}", ""]
        if not t.has_contract and t.pii_columns:
            lines += [
                "**No contract.** This table holds personal data but nobody has declared it.",
                "",
            ]
        lines += [
            "| Column | Type | Personal data | How it is known | Scanner confidence |",
            "| --- | --- | --- | --- | --- |",
        ]
        for c in t.columns:
            confidence = None if c.confidence is None else f"{c.confidence:.0%}"
            lines.append(
                f"| {_cell(c.name)} | {_cell(c.data_type)} | {_cell(c.pii_type)} "
                f"| {_cell(c.source)} | {_cell(confidence)} |"
            )
    return "\n".join(lines) + "\n"
