"""Data contracts: the human-owned declaration of what personal data a table holds.

The scanner says what it *found*; the contract says what the team *declared*. `check` compares
the two. Generated contracts are only a starting point: owner and retention are left empty on
purpose, because a tool cannot know who is responsible for a table.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from data_warden.scan import Finding

_FIELDS = {"table", "owner", "retention_days", "pii_columns"}
_HEADER = (
    "# Data contract. Generated by data-warden, then owned by humans.\n"
    "# owner: who answers questions about this table.\n"
    "# retention_days: how long personal data may be kept.\n"
    "# pii_columns: column -> personal data type. Add columns the scanner cannot detect.\n"
)


class ContractError(ValueError):
    """A contract file is unreadable or has the wrong shape."""


@dataclass(frozen=True)
class Contract:
    table: str
    owner: str | None = None
    retention_days: int | None = None
    pii_columns: dict[str, str] = field(default_factory=dict)


def parse_contract(data: object, source: str) -> Contract:
    if not isinstance(data, dict):
        raise ContractError(f"{source}: expected a mapping at the top level")
    unknown = set(data) - _FIELDS
    if unknown:
        # Strict on purpose: a typo like `retention_day` must not silently read as "missing".
        raise ContractError(f"{source}: unknown field(s): {', '.join(sorted(map(str, unknown)))}")
    table, owner = data.get("table"), data.get("owner")
    retention, pii = data.get("retention_days"), data.get("pii_columns") or {}
    if not isinstance(table, str) or not table:
        raise ContractError(f"{source}: `table` must be a non-empty string")
    if owner is not None and not isinstance(owner, str):
        raise ContractError(f"{source}: `owner` must be text or null")
    if retention is not None and (
        isinstance(retention, bool) or not isinstance(retention, int) or retention <= 0
    ):
        raise ContractError(f"{source}: `retention_days` must be a positive whole number or null")
    if not isinstance(pii, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in pii.items()
    ):
        raise ContractError(f"{source}: `pii_columns` must map column names to type names")
    return Contract(table, owner, retention, dict(pii))


def load_contracts(directory: Path) -> dict[str, Contract]:
    contracts: dict[str, Contract] = {}
    paths = sorted([*directory.glob("*.yaml"), *directory.glob("*.yml")])
    for path in paths:
        try:
            data: Any = yaml.safe_load(path.read_text())
        except yaml.YAMLError as error:
            raise ContractError(f"{path}: invalid YAML ({error})") from error
        contract = parse_contract(data, str(path))
        if contract.table in contracts:
            raise ContractError(f"{path}: table `{contract.table}` is defined twice")
        contracts[contract.table] = contract
    return contracts


def render_contract(contract: Contract) -> str:
    body = {
        "table": contract.table,
        "owner": contract.owner,
        "retention_days": contract.retention_days,
        "pii_columns": dict(sorted(contract.pii_columns.items())),
    }
    return _HEADER + yaml.safe_dump(body, sort_keys=False)


def contracts_from_findings(findings: list[Finding]) -> list[Contract]:
    """One skeleton contract per table that has findings."""
    by_table: dict[str, dict[str, str]] = defaultdict(dict)
    for f in findings:
        by_table[f.table][f.column] = f.pii_type
    return [Contract(table, pii_columns=cols) for table, cols in sorted(by_table.items())]


def write_missing_contracts(
    contracts: list[Contract], directory: Path
) -> tuple[list[Path], list[Path]]:
    """Write contracts that do not exist yet. Existing files are never touched.

    Returns (created, skipped).
    """
    directory.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    skipped: list[Path] = []
    for contract in contracts:
        filename = re.sub(r"[^\w.-]", "_", contract.table)
        path = directory / f"{filename}.yaml"
        if path.exists():
            skipped.append(path)
        else:
            path.write_text(render_contract(contract))
            created.append(path)
    return created, skipped
